/**
 * Hub Common Response
 *
 * Copyright (C) 2017 Black Duck Software, Inc.
 * http://www.blackducksoftware.com/
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
/*
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.blackducksoftware.integration.hub.model.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.blackducksoftware.integration.hub.model.HubView;
import com.blackducksoftware.integration.hub.model.enumeration.MatchedFileUsageEnum;
import com.blackducksoftware.integration.hub.model.view.components.ActivityDataView;
import com.blackducksoftware.integration.hub.model.view.components.RiskProfileView;
import com.blackducksoftware.integration.hub.model.view.components.VersionBomLicenseView;
import com.google.gson.annotations.SerializedName;

public class VersionBomComponentView extends HubView {
    @SerializedName("activityData")
    private ActivityDataView activityData = null;

    @SerializedName("activityRiskProfile")
    private RiskProfileView activityRiskProfile = null;

    @SerializedName("component")
    private String component = null;

    @SerializedName("componentName")
    private String componentName = null;

    @SerializedName("componentVersion")
    private String componentVersion = null;

    @SerializedName("componentVersionName")
    private String componentVersionName = null;

    @SerializedName("licenseRiskProfile")
    private RiskProfileView licenseRiskProfile = null;

    @SerializedName("licenses")
    private List<VersionBomLicenseView> licenses = new ArrayList<>();

    @SerializedName("operationalRiskProfile")
    private RiskProfileView operationalRiskProfile = null;

    @SerializedName("releasedOn")
    private Date releasedOn = null;

    @SerializedName("securityRiskProfile")
    private RiskProfileView securityRiskProfile = null;

    @SerializedName("usages")
    private List<MatchedFileUsageEnum> usages = new ArrayList<>();

    @SerializedName("versionRiskProfile")
    private RiskProfileView versionRiskProfile = null;

    public ActivityDataView getActivityData() {
        return activityData;
    }

    public void setActivityData(final ActivityDataView activityData) {
        this.activityData = activityData;
    }

    public RiskProfileView getActivityRiskProfile() {
        return activityRiskProfile;
    }

    public void setActivityRiskProfile(final RiskProfileView activityRiskProfile) {
        this.activityRiskProfile = activityRiskProfile;
    }

    public String getComponent() {
        return component;
    }

    public void setComponent(final String component) {
        this.component = component;
    }

    public String getComponentName() {
        return componentName;
    }

    public void setComponentName(final String componentName) {
        this.componentName = componentName;
    }

    public String getComponentVersion() {
        return componentVersion;
    }

    public void setComponentVersion(final String componentVersion) {
        this.componentVersion = componentVersion;
    }

    public String getComponentVersionName() {
        return componentVersionName;
    }

    public void setComponentVersionName(final String componentVersionName) {
        this.componentVersionName = componentVersionName;
    }

    public RiskProfileView getLicenseRiskProfile() {
        return licenseRiskProfile;
    }

    public void setLicenseRiskProfile(final RiskProfileView licenseRiskProfile) {
        this.licenseRiskProfile = licenseRiskProfile;
    }

    public List<VersionBomLicenseView> getLicenses() {
        return licenses;
    }

    public void setLicenses(final List<VersionBomLicenseView> licenses) {
        this.licenses = licenses;
    }

    public RiskProfileView getOperationalRiskProfile() {
        return operationalRiskProfile;
    }

    public void setOperationalRiskProfile(final RiskProfileView operationalRiskProfile) {
        this.operationalRiskProfile = operationalRiskProfile;
    }

    public Date getReleasedOn() {
        return releasedOn;
    }

    public void setReleasedOn(final Date releasedOn) {
        this.releasedOn = releasedOn;
    }

    public RiskProfileView getSecurityRiskProfile() {
        return securityRiskProfile;
    }

    public void setSecurityRiskProfile(final RiskProfileView securityRiskProfile) {
        this.securityRiskProfile = securityRiskProfile;
    }

    public List<MatchedFileUsageEnum> getUsages() {
        return usages;
    }

    public void setUsages(final List<MatchedFileUsageEnum> usages) {
        this.usages = usages;
    }

    public RiskProfileView getVersionRiskProfile() {
        return versionRiskProfile;
    }

    public void setVersionRiskProfile(final RiskProfileView versionRiskProfile) {
        this.versionRiskProfile = versionRiskProfile;
    }
}
